name: wallet_connect
description: Wallet Connect client made in love with dart.
version: 1.0.0
homepage: https://github.com/Orange-Wallet/wallet-connect-dart

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  hex: ^0.1.2
  web_socket_channel: ^1.2.0
  uuid: ^3.0.4
  http: ^0.12.2
  cryptography: ^2.0.2
  json_annotation: ^3.1.1
  meta: ^1.2.4

dev_dependencies:
  build_runner:
  json_serializable: ^3.5.1
